### ISSUE TITLE
Prevent automatic software whitelisting

### ISSUE THREAD

**Issue by thistehneisen** [alichtman/stronghold#63]
```
 -> Prevent automatic software whitelisting?
[?] Both built-in and downloaded software will require user approval for whitelisting.:  Yes
 >  Yes
    No

Preventing automatic whitelisting...

Traceback (most recent call last):
  File "/usr/local/bin/stronghold", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/stronghold.py", line 375, in cli
    system_protection_config()
  File "/usr/local/lib/python2.7/site-packages/stronghold.py", line 149, in system_protection_config
    sp.run(['sudo', '/usr/libexec/ApplicationFirewall/socketfilterfw', '--setallowsigned', 'off'], stdout=sp.PIPE)
AttributeError: 'module' object has no attribute 'run'

```

**Comment by alichtman** [comment]
Python 2.7 is unsupported. Try with Python 3.

https://github.com/alichtman/stronghold/issues/52#issuecomment-413392278
